use strict;
use warnings;
use Test::More;
use File::Temp qw(tempdir);
use File::Spec;
use IPC::Open3;
use Symbol qw(gensym);
use JSON::PP;

my $dir = tempdir(CLEANUP => 1);
sub fixture {
    my ($name, $bytes) = @_;
    my $file = File::Spec->catfile($dir, $name);
    open my $fh, '>:raw', $file or die $!;
    print {$fh} $bytes;
    close $fh or die $!;
    return $file;
}
sub run_cli {
    my (@args) = @_;
    my $err = gensym;
    my $pid = open3(my $in, my $out, $err, $^X, '-Ilib', 'script/html-anchor-audit', @args);
    close $in;
    my $stdout = do { local $/; <$out> } // '';
    my $stderr = do { local $/; <$err> } // '';
    waitpid($pid, 0);
    return ($? >> 8, $stdout, $stderr);
}
my $good = fixture('clean article.html', '<a href="#x"></a><h2 id="x"></h2>');
my $bad = fixture('bad.html', '<a href="#gone"></a>');
my ($code, $out, $err) = run_cli($good);
is($code, 0, 'clean file exit 0');
like($out, qr/0 issue\(s\), 1 checked/, 'text summary');
is($err, '', 'no error on clean file');
($code, $out, $err) = run_cli('--json', $good, $bad);
is($code, 1, 'diagnostics exit 1');
my $data = JSON::PP->new->utf8->decode($out);
is(scalar @{ $data->{files} }, 2, 'multiple files in one JSON object');
is($data->{files}[1]{report}{issues}[0]{code}, 'missing_target', 'structured diagnostic');
is($data->{files}[0]{file}, $good, 'filename with space survives argument passing');
is($err, '', 'JSON mode errors stay structured');
open my $fh, '<:raw', $bad or die $!;
is(do { local $/; <$fh> }, '<a href="#gone"></a>', 'input file preserved');
close $fh;
($code, $out, $err) = run_cli('--json', File::Spec->catfile($dir, 'missing.html'), $good);
is($code, 2, 'file error exit 2');
$data = JSON::PP->new->utf8->decode($out);
ok($data->{files}[0]{error}, 'file error in JSON');
ok($data->{files}[1]{report}, 'other files still checked after an error');
($code, $out, $err) = run_cli('--json', fixture('invalid.html', "\xFF"));
is($code, 2, 'invalid UTF-8 exit 2');
like(JSON::PP->new->utf8->decode($out)->{files}[0]{error}, qr/not valid UTF-8/, 'clear UTF-8 error');
($code, $out, $err) = run_cli('--json', '--max-bytes', '3', $good);
is($code, 2, 'file-size limit exit 2');
($code, $out, $err) = run_cli('--json', 'https://example.invalid/');
is($code, 2, 'URL mode forbidden');
like(JSON::PP->new->utf8->decode($out)->{files}[0]{error}, qr/URLs are not accepted/, 'network intent rejected');
($code, $out, $err) = run_cli('--bogus', $good);
is($code, 2, 'unknown option exit 2');
($code, $out, $err) = run_cli();
is($code, 2, 'missing filename exit 2');
($code, $out, $err) = run_cli('--help');
is($code, 0, 'help exit 0');
like($out, qr/Offline/, 'help explains offline mode');
($code, $out, $err) = run_cli('--version');
is($code, 0, 'version exit 0');
like($out, qr/0\.001/, 'version output');
($code, $out, $err) = run_cli('--max-issues', '1', fixture('many.html', '<a href="#a"></a><a href="#b"></a>'));
is($code, 1, 'capped issues still cause failure');
like($out, qr/truncated/, 'text output makes truncation explicit');
done_testing;
